PayRollProject/Areas/AdminArea/Controllers/CityManagementController.cs
using Microsoft.AspNetCore.Mvc;

namespace PayRollProject.Areas.AdminArea.Controllers
{
	public class CityManagementController : Controller
	{
		// GET
		public IActionResult Index()
		{
			return View();
		}
	}
}

PayRollProject/Areas/AdminArea/Controllers/CountryManagementController.cs
namespace PayRollProject.Areas.AdminArea.Controllers
{
	using System.Collections;
	using Entities.Entities;
	using Microsoft.AspNetCore.Authorization;
	using Microsoft.AspNetCore.Identity;
	using Syncfusion.EJ2.Base;

	[Area("AdminArea")]
    [Authorize]
    public class CountryManagementController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly IBaseTableRepository _repository;
        private readonly UserManager<ApplicationUsers> _userManager;

        public CountryManagementController(IUnitOfWork context, IBaseTableRepository repository, UserManager<ApplicationUsers> userManager)
        {
            this._context = context;
            this._repository = repository;
            this._userManager = userManager;
        }

        // GET
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FetchCountryList([FromBody] DataManagerRequest dm)
        {
            IEnumerable dataSource = this._context.CountriesUw.Get();
            var dt = dataSource.Cast<Countries>();
            int count = dt.Count();

            DataOperations operation = new DataOperations();
            if (dm.Search != null && dm.Search.Count > 0)
            {
                dataSource = operation.PerformSearching(dataSource, dm.Search); // جستجو
            }

            if (dm.Sorted != null && dm.Sorted.Count > 0)
            {
                dataSource = operation.PerformSorting(dataSource, dm.Sorted); // مرتب کردن
            }

            if (dm.Where != null && dm.Where.Count > 0)
            {
                dataSource = operation.PerformFiltering(dataSource, dm.Where, dm.Where[0].Operator); // filtering
            }

            if (dm.Skip != 0)
            {
                dataSource = operation.PerformSkip(dataSource, dm.Skip);
            }

            if (dm.Take != 0)
            {
                dataSource = operation.PerformTake(dataSource, dm.Take);
            }

            return dm.RequiresCounts
                ? Json(new
                {
	                result = dataSource,
	                action = "fetchGrid",
	                count = count
                })
                : Json(dataSource);
        }

        public IActionResult Insert([FromBody] CRUDModel<Countries> model)
        {
            try
            {
                var countries = this._context.CountriesUw.Get();
                Countries country = new Countries
                {
                    CountryName = model.Value.CountryName,
                    Description = model.Value.Description,
                    CreateDateTime = DateTime.Now,
                    UserID = this._userManager.GetUserId(this.HttpContext.User) ?? "System"
                };
                if (countries.Any((Countries c) => c.CountryName == country.CountryName))
                {
                    return Json(new { action = "repeat", country = country.CountryName });
                }
                else
                {
                    this._context.CountriesUw.Create(country);
                    this._context.Save();
                    return Json(new { action = "insert", country = country.CountryName });
                }
            }
            catch (Exception e)
            {
                return Json(new
                {
	                action = "error",
	                ErrMsg = e.Message
                });
            }
        }

        public IActionResult Update([FromBody] CRUDModel<Countries> model)
        {
            try
            {
                this._repository.UpdateCountry(model);

                return Json(new { action = "update", country = model.Value.CountryName });
            }
            catch (Exception e)
            {
                return Json(new { action = "error", ErrMsg = e.Message });
            }
        }

        public IActionResult Delete([FromBody] CRUDModel<Countries> model)
        {
            try
            {
                string? key = model.Key.ToString();
                var country = this._context.CountriesUw.GetById(Convert.ToInt32(key));
                this._context.CountriesUw.DeleteById(Convert.ToInt32(key));
                this._context.Save();
                return Json(new { action = "delete", country = country.CountryName });
            }
            catch (Exception e)
            {
                return Json(new { action = "error", ErrMsg = e.Message });
            }
        }
    }
}

PayRollProject/Areas/AdminArea/Controllers/UserManagerController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="UserManagerController.cs" company="">
//   
// </copyright>
// <summary>
//   Defines the UserManagerController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using Microsoft.AspNetCore.SignalR;

namespace PayRollProject.Areas.AdminArea.Controllers
{
	using System.Collections;
	using Entities.Entities;
	using Entities.Models;
	using Microsoft.AspNetCore.Authorization;
	using Microsoft.AspNetCore.Identity;
	using Microsoft.AspNetCore.Mvc;
	using Syncfusion.EJ2.Base;

	[Area("AdminArea")]
	[Authorize]
	public class UserManagerController : Controller
	{
		private readonly IUnitOfWork _context;
		private readonly IUserRepository _user;
		private readonly UserManager<ApplicationUsers> _userManager;

		public UserManagerController(IUnitOfWork context, IUserRepository user,
			UserManager<ApplicationUsers> userManager)
		{
			_context = context;
			_user = user;
			_userManager = userManager;
		}

		// GET
		// [HttpGet]
		// public async Task<IActionResult> Index()
		// {
		// 	var userId = _userManager.GetUserId(User);
		// 	object currentUserVm;
		// 	if (userId != null)
		// 	{
		// 		var user = await _userManager.FindByIdAsync(userId);
		// 		if (user != null)
		// 		{
		// 			currentUserVm = new
		// 			{
		// 				user.Id,
		// 				user.FirstName,
		// 				user.Family,
		// 				user.Email,
		// 				user.PhoneNumber
		// 			};
		// 			this.ViewData["CurrentUserVm"] = currentUserVm;
		// 		}
		// 	}
		//
		// 	return View();
		// }
		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		// public async Task<IActionResult> GetCurrentUser()
		// {
		// 	var userId = this._userManager.GetUserId(this.User);
		// 	if (userId == null) return Json(null);
		//
		// 	var user = await this._userManager.FindByIdAsync(userId);
		// 	if (user == null) return Json(null);
		//
		// 	var vm = new
		// 	{
		// 		user.Id,
		// 		user.FirstName,
		// 		user.Family,
		// 		user.Email,
		// 		user.PhoneNumber
		// 	};
		// 	return Json(vm);
		// }

		public IActionResult FetchUserList([FromBody] DataManagerRequest dataManager)
		{
			IEnumerable dataSource = this._user.GetUserList();
			var all = dataSource.Cast<UserListDTO>();
			int countAllUser = all.Count();
			int countActiveUser = all.Count((UserListDTO u) => u.UserFlag == 1);
			int countDeactivateUser = all.Count((UserListDTO u) => u.UserFlag == 2);


			DataOperations operations = new DataOperations();

			if (dataManager.Search != null && dataManager.Search.Count > 0)
			{
				dataSource = operations.PerformSearching(dataSource, dataManager.Search); // Searching جشتجوکردن
			}

			if (dataManager.Sorted?.Count > 0)
			{
				dataSource = operations.PerformSorting(dataSource, dataManager.Sorted); // Sorting مرتب سازی
			}

			if (dataManager.Where?.Count > 0)
			{
				dataSource =
					operations.PerformFiltering(dataSource, dataManager.Where,
						dataManager.Where[0].Operator); // Filtering فیلترکردن
			}

			var filteredCount = dataSource.Cast<UserListDTO>().Count();

			if (dataManager.Skip != 0)
			{
				dataSource = operations.PerformSkip(dataSource, dataManager.Skip);
			}

			if (dataManager.Take != 0)
			{
				dataSource = operations.PerformTake(dataSource, dataManager.Take);
			}

			return dataManager.RequiresCounts
				? Json(new
				{
					result = dataSource,
					action = "fetchGrid",
					count = filteredCount,
					countAll = countAllUser,
					countActive = countActiveUser,
					countDeactivate = countDeactivateUser
				})
				: Json(dataSource);
		}

		public async Task<IActionResult> Insert([FromBody] CRUDModel<UserListDTO> model)
		{
			try
			{
				var getUser = this._context.UserManager
					.Get((ApplicationUsers u) => u.UserName == model.Value.MelliCode);
				if (getUser.Any())
				{
					// تکراری
					return Json(new
					{
						action = "repeatUser",
						user = model.Value.FirstName + " " + model.Value.Family,
						melli = model.Value.MelliCode
					});
				}

				var newUser = new ApplicationUsers
				{
					FirstName = model.Value.FirstName,
					Family = model.Value.Family,
					PhoneNumber = model.Value.PhoneNumber,
					Email = model.Value.Email,
					MelliCode = model.Value.MelliCode,
					UserName = model.Value.MelliCode,
					Gender = Convert.ToByte(model.Value.GenderText),
					UserType = Convert.ToByte(model.Value.UserTypeText),
					UserFlag = 1 // default is Active
				};

				// ایجاد کاربر
				IdentityResult result = await this._userManager.CreateAsync(newUser, "123456");
				if (result.Succeeded)
				{
					// تنظیم نقش کاربر
					if (model.Value.UserTypeText == "1")
					{
						// کاربر ادمین
						await this._userManager.AddToRoleAsync(newUser, "adminPanel");
					}
					else if (model.Value.UserTypeText == "2")
					{
						// کاربر عادی
						await this._userManager.AddToRoleAsync(newUser, "userPanel");
					}
				}

				this._context.SaveAsync();
				return Json(new { action = "insert", user = newUser.FirstName + " " + newUser.Family });
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				return Json(new { action = "error", ErrMsg = e.Message, text = e.Data });
			}
		}

		public async Task<IActionResult> Update([FromBody] CRUDModel<UserListDTO> model)
		{
			try
			{
				var currentUser = await this._userManager.FindByIdAsync(model.Value.Id);
				if (currentUser == null)
				{
					return Json(new { action = "notFound" });
				}

				currentUser.FirstName = model.Value.FirstName;
				currentUser.Family = model.Value.Family;
				currentUser.PhoneNumber = model.Value.PhoneNumber;
				currentUser.Email = model.Value.Email;
				currentUser.Gender = Convert.ToByte(model.Value.GenderText);


				IdentityResult result = await this._userManager.UpdateAsync(currentUser);
				if (result.Succeeded)
				{
					return Json(new { action = "update", user = currentUser.FirstName + " " + currentUser.Family });
				}
				else
				{
					return Json(new
					{
						action = "error",
						ErrMsg = "ظاهرا خطایی رخ داده لطفا با ادمین تماس بگیرید",
						text = "خطای مربوط به ذخیره سازی در سرور"
					});
				}
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				return Json(new { action = "error", ErrMsg = e.Message, text = e.Data });
			}
		}

		[HttpPost]
		public async Task<IActionResult> DeactivateUser([FromBody] CRUDModel<UserListDTO> model)
		{
			_user.DeactivateUser(model.Value.MelliCode);
			if (!this.ModelState.IsValid)
			{
				return Json(new
				{
					action = "error",
					ErrMsg = "خطا در ارتباط با فعال  و غیر فعال کردن",
					text = "متاسفانه نتوانستیم کاربر مورد نظر را غیر فعال کنیم."
				});
			}

			return Json(new { action = "deactivate", user = model.Value.FirstName + " " + model.Value.Family });
		}

		[HttpPost]
		public async Task<IActionResult> ActiveUser([FromBody] CRUDModel<UserListDTO> model)
		{
			this._user.ActiveUser(model.Value.MelliCode);
			if (!this.ModelState.IsValid)
			{
				return Json(new
				{
					action = "error",
					ErrMsg = "خطا در ارتباط با فعال  و غیر فعال کردن",
					text = "متاسفانه نتوانستیم کاربر مورد نظر را غیر فعال کنیم."
				});
			}

			return Json(new { action = "deactivate", user = model.Value.FirstName + " " + model.Value.Family });
		}
	}
}

PayRollProject/Areas/AdminArea/ViewComponents/CurrentUserViewComponent.cs
namespace PayRollProject.Areas.AdminArea.ViewComponents
{
	using Microsoft.AspNetCore.Identity;
	using PayRollProject.Entities.Entities;
	using ViewModels;

	public class CurrentUserViewComponent : ViewComponent
	{
		private readonly UserManager<ApplicationUsers> _userManager;

		public CurrentUserViewComponent(UserManager<ApplicationUsers> userManager)
		{
			this._userManager = userManager;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var userId = this._userManager.GetUserId(this.HttpContext.User);
			if (string.IsNullOrEmpty(userId)) return View(null);

			var user = await this._userManager.FindByIdAsync(userId);
			if (user == null) return View(null);

			var vm = new CurrentUserViewModel
			{
				Id = user.Id,
				FirstName = user.FirstName,
				Family = user.Family,
				Email = user.Email,
				IsActive = user.UserFlag != 2,
				PhoneNumber = user.PhoneNumber
			};
			return View(vm);
		}
	}
}

PayRollProject/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html class="loading" lang="fa" data-textdirection="rtl" dir="rtl">
<!-- BEGIN: Head-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>حقوق و دستمزد مهدی - @ViewData["AdminTitle"]</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/icon/favicon.ico">
    <meta name="theme-color" content="#5A8DEE">

    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/vendors/css/vendors.min.css">
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/vendors/css/charts/apexcharts.css">
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/vendors/css/extensions/swiper.min.css">
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/vendors/css/ui/material.css"/>
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/css/bootstrap-extended.css">
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/css/colors.css">
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/css/components.css">
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/css/themes/dark-layout.css">
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/css/themes/semi-dark-layout.css">
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/css/core/menu/menu-types/vertical-menu.css">
    <link rel="stylesheet" type="text/css" asp-append-version="true" href="~/assets/fontawesome-pro-5.8.2-web/css/fontawesome-pro-5.8.2.css">

    <!-- Syncfusion ASP.NET Core controls styles -->
    <link rel="stylesheet" asp-append-version="true" href="https://cdn.syncfusion.com/ej2/29.1.33/material.css"/>

</head>
<!-- END: Head-->
<!-- BEGIN: Body-->
<body class="vertical-layout vertical-menu-modern semi-dark-layout 2-columns navbar-sticky footer-static" data-open="click" data-menu="vertical-menu-modern" data-col="2-columns" data-layout="semi-dark-layout">

<div class="header-navbar-shadow"></div>

<partial name="_RightMenu"/>
<partial name="_ExtensionMenu"/>

<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        @RenderBody()
    </div>
</div>


<div class="sidenav-overlay"></div>
<div class="drag-target"></div>

<!--modal when ajax request is sending-->
<div class="modal"></div>

<!-- BEGIN: Footer-->
<footer class="footer footer-static footer-light">
    <p class="clearfix mb-0">
        <button class="btn btn-primary btn-icon scroll-top" type="button">
            <i class="bx bx-up-arrow-alt"></i>
        </button>
    </p>
</footer>
<!-- END: Footer-->
<!-- BEGIN: Vendor JS-->

<!-- Syncfusion ASP.NET Core controls scripts -->
<script asp-append-version="true" src="https://cdn.syncfusion.com/ej2/29.1.33/dist/ej2.min.js"></script>
<script asp-append-version="true" src="~/assets/vendors/js/vendors.min.js"></script>
<script asp-append-version="true" src="~/assets/fonts/LivIconsEvo/js/LivIconsEvo.tools.min.js"></script>
<script asp-append-version="true" src="~/assets/fonts/LivIconsEvo/js/LivIconsEvo.defaults.js"></script>
<script asp-append-version="true" src="~/assets/fonts/LivIconsEvo/js/LivIconsEvo.min.js"></script>
<!-- BEGIN Vendor JS-->
<!-- BEGIN: Ali js-->
<script asp-append-version="true" src="~/assets/fontawesome-pro-5.8.2-web/js/fontawesome-pro-5.8.2.js"></script>
@*<script src="~/lib/toastr.js/toastr.min.js" asp-append-version="true"></script>*@
<!-- END: Ali js-->
<!-- BEGIN: Theme JS-->
<script asp-append-version="true" src="~/assets/js/scripts/configs/vertical-menu-dark.js"></script>
<script asp-append-version="true" src="~/assets/js/core/app-menu.js"></script>
<script asp-append-version="true" src="~/assets/js/core/app.js"></script>
<script asp-append-version="true" src="~/assets/js/scripts/components.js"></script>
<script asp-append-version="true" src="~/assets/js/scripts/footer.js"></script>
<script asp-append-version="true" src="~/assets/js/scripts/customizer.js"></script>
<!-- END: Theme JS-->
<!-- BEGIN: Page Vendor JS-->
<script asp-append-version="true" src="~/assets/vendors/js/ui/jquery.sticky.js"></script>

<script>
    let ajax = new ej.base.Ajax(location.origin + '/../../locale/fa.json','GET',false); // بارگزاری فایل فرهنگ و ترجمه
    ajax.send().then((e) => {
        let loader = JSON.parse(e);
        ej.base.L10n.load(
            loader
        );
        ej.base.setCulture('fa'); // فعال کردن 
    });
</script>


<!-- END: Page Vendor JS-->
@await RenderSectionAsync("AdminScripts", false)

<ejs-scripts></ejs-scripts>
</body>
<!-- END: Body-->
</html>

PayRollProject/Areas/AdminArea/Views/Shared/_RightMenu.cshtml
<div class="main-menu menu-fixed menu-dark menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="navbar-header">
        <ul class="nav navbar-nav flex-row">
            <li class="nav-item mr-auto">
                <a class="navbar-brand" href="#">
                    <div class="brand-logo">
                        <i class="fas fa-home"></i>
                    </div>
                    <h6 class="brand-text mb-0" style="font-size: 18px;">داشبورد مدير</h6>
                </a>
            </li>
            <li class="nav-item nav-toggle">
                <a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse">
                    <i class="bx bx-x d-block d-xl-none font-medium-4 primary"></i><i class="toggle-icon bx bx-disc font-medium-4 d-none d-xl-block primary" data-ticon="bx-disc"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="shadow-bottom"></div>
    <div class="main-menu-content">
        <ul style="font-size: 14px;" class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation" data-icon-style="lines">
            <li class="navigation-header">
                <span style="font-size: 15px;">امکانات سيستم</span>
            </li>

            <li class="is-shown">
                <a asp-action="Index" asp-controller="UserManager" asp-area="AdminArea" class="nav-link">
                    <i class="menu-livicon" data-icon="users"></i>
                    <span>ليست کاربران سيستم</span>
                </a>
            </li>

            <li class="nav-item has-sub">
                <a href="#">
                    <i class="menu-livicon livicon-evo-holder" data-icon="morph-doc">
                    </i><span class="menu-title">اطلاعات پايه</span>
                </a>
                <ul class="navigation navigation-main" data-menu="menu-navigation" data-icon-style="lines">
                    <li class="is-shown">
                        <a asp-action="Index" asp-controller="CountryManagement" asp-area="AdminArea" style="font-size: 12px;">
                            <i class="menu-livicon" data-icon="location"></i>
                            <span>ليست کشورها</span>
                        </a>
                    </li>
                    <li class="is-shown">
	                    <a asp-action="Index" asp-controller="ProvinceManagement" asp-area="AdminArea" style="font-size: 12px;">
		                    <i class="menu-livicon" data-icon="building"></i>
		                    <span>ليست استان ها</span>
	                    </a>
                    </li>
					<li class="is-shown">
						<a asp-action="Index" asp-controller="CityManagement" asp-area="AdminArea" style="font-size: 12px;">
							<i class="menu-livicon" data-icon="building"></i>
							<span>ليست شهرها</span>
						</a>
					</li>

                </ul>
            </li>

        </ul>
    </div>
</div>

PayRollProject/Areas/AdminArea/Views/Shared/_extensionMenu.cshtml
<nav class="header-navbar main-header-navbar navbar-expand-lg navbar navbar-with-menu fixed-top">
	<div class="navbar-wrapper">
		<div class="navbar-container content">
			<div class="navbar-collapse" id="navbar-mobile">
				<div class="bookmark-wrapper d-flex align-items-center float-left mr-auto">
					<ul class="nav navbar-nav">
						<li class="nav-item mobile-menu d-xl-none mr-auto">
							<a class="nav-link nav-menu-main menu-toggle hidden" href="#">
								<i class="ficon bx bx-menu"></i>
							</a>
						</li>
					</ul>
					<ul class="nav navbar-nav bookmark-icons">
						<li class="nav-item d-none d-lg-block">
							<a class="nav-link" href="app-email.html" data-toggle="tooltip" data-placement="bottom" title="ايميل">
								<i class="ficon bx bx-envelope"></i>
							</a>
						</li>
						<li class="nav-item d-none d-lg-block">
							<a class="nav-link" href="app-chat.html" data-toggle="tooltip" data-placement="bottom" title="گفتگو">
								<i class="ficon bx bx-chat"></i>
							</a>
						</li>
						<li class="nav-item d-none d-lg-block">
							<a class="nav-link" href="app-todo.html" data-toggle="tooltip" data-placement="bottom" title="وظايف">
								<i class="ficon bx bx-check-circle"></i>
							</a>
						</li>
						<li class="nav-item d-none d-lg-block">
							<a class="nav-link" href="app-calendar.html" data-toggle="tooltip" data-placement="bottom" title="تقويم">
								<i class="ficon bx bx-calendar-alt"></i>
							</a>
						</li>
					</ul>
					<ul class="nav navbar-nav">
						<li class="nav-item d-none d-lg-block">
							<a class="nav-link bookmark-star">
								<i class="ficon bx bx-star warning"></i>
							</a>
							<div class="bookmark-input search-input">
								<div class="bookmark-input-icon">
									<i class="bx bx-search primary"></i>
								</div>
								<input class="form-control input" type="text" placeholder="جستجو ..." tabindex="0" data-search="template-search">
								<ul class="search-list"></ul>
							</div>
						</li>
					</ul>
				</div>
				<ul class="nav navbar-nav float-right">
					<li class="dropdown dropdown-language nav-item">
						<a class="dropdown-toggle nav-link" id="dropdown-flag" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="flag-icon flag-icon-ir"></i><span class="selected-language">فارسي</span>
						</a>

					</li>
					<li class="nav-item d-none d-lg-block">
						<a class="nav-link nav-link-expand">
							<i class="ficon bx bx-fullscreen"></i>
						</a>
					</li>
					<li class="nav-item nav-search">
						<a class="nav-link nav-link-search">
							<i class="ficon bx bx-search"></i>
						</a>
						<div class="search-input">
							<div class="search-input-icon">
								<i class="bx bx-search primary"></i>
							</div>
							<input class="input" type="text" placeholder="جستجو ..." tabindex="-1" data-search="template-search">
							<div class="search-input-close">
								<i class="bx bx-x"></i>
							</div>
							<ul class="search-list"></ul>
						</div>
					</li>
					<li class="dropdown dropdown-notification nav-item">
						<a class="nav-link nav-link-label" href="#" data-toggle="dropdown">
							<i class="ficon bx bx-bell bx-tada bx-flip-horizontal"></i><span class="badge badge-pill badge-danger badge-up">5</span>
						</a>

					</li>
					<form asp-area="" asp-controller="Account" asp-action="LogOut" method="post">
					<li class="dropdown dropdown-user nav-item">
						<a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
							@await Component.InvokeAsync("CurrentUser")
						</a>
						<div class="dropdown-menu pb-0">
							<a class="dropdown-item" asp-controller="User" asp-action="Edit"><i class="bx bx-user mr-50"></i> ويرايش پروفايل</a>
							<a class="dropdown-item" asp-controller="Workspace" asp-action="Edit"><i class="bx bx-cog mr-50"></i> تنظيمات فضاي کاري</a>
							<a class="dropdown-item" asp-controller="User" asp-action="ChangePassword"><i class="bx bx-lock-alt mr-50"></i> تغيير رمز عبور</a>
							@* <div class="dropdown-divider mb-0"></div> *@
							@* <a class="dropdown-item" asp-controller="Account" asp-action="Logout"><i class="bx bx-power-off mr-50"></i> خروج</a> *@
							<button type="submit" class="dropdown-item"><i class="bx bx-power-off mr-50"></i>خروج از سیستم</button>
						</div>
					</li>
					</form>
				</ul>
			</div>
		</div>
	</div>
</nav>