PayRollProject/Areas/AdminArea/Controllers/ProvinceManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PayRollProject.Entities.Entities;
using Syncfusion.EJ2.Base;

namespace PayRollProject.Areas.AdminArea.Controllers
{
	[Area("AdminArea")]
	[Authorize]
	public class ProvinceManagementController : Controller
	{
		private readonly IUnitOfWork _context;
		private readonly IBaseTableRepository _repository;
		private readonly UserManager<ApplicationUsers> _userManager;

		public ProvinceManagementController(IUnitOfWork context, IBaseTableRepository repository,
			UserManager<ApplicationUsers> userManager)
		{
			this._context = context;
			this._repository = repository;
			this._userManager = userManager;
		}


		// GET
		public IActionResult Index()
		{
			return View();
		}

                public IActionResult FetchProvinceList([FromBody] DataManagerRequest dm, string mode = "")
                {
                        var provinces = this._context.ProvincesUw.Get().ToArray();
                        IEnumerable<ProvinceTbl> dataSource;

                        if (mode == "all")
                        {
                                dataSource = provinces;
                        }
                        else if (mode == "delete")
                        {
                                dataSource = provinces.Where(p => p.IsDelete);
                        }
                        else
                        {
                                dataSource = provinces.Where(p => !p.IsDelete);
                        }

                        var op = new DataOperations();
                        if (dm.Search != null && dm.Search.Count > 0)
                        {
                                dataSource = op.PerformSearching(dataSource, dm.Search); // search
                        }

                        if (dm.Sorted != null && dm.Sorted.Count > 0)
                        {
                                dataSource = op.PerformSorting(dataSource, dm.Sorted); // sort
                        }

                        if (dm.Where != null && dm.Where.Count > 0)
                        {
                                dataSource = op.PerformFiltering(dataSource, dm.Where, dm.Where[0].Operator); // filter
                        }

                        var filteredCount = dataSource.Count();

                        if (dm.Skip != 0)
                        {
                                dataSource = op.PerformSkip(dataSource, dm.Skip); // paging: skip
                        }

                        if (dm.Take != 0)
                        {
                                dataSource = op.PerformTake(dataSource, dm.Take); // paging: take
                        }

                        return dm.RequiresCounts
                                ? Json(new
                                {
                                        result = dataSource,
                                        action = "fetchGridProvince",
                                        countAll = provinces.Length,
                                        countDelete = provinces.Count(p => p.IsDelete),
                                        count = filteredCount
                                })
                                : Json(dataSource);
                }

		public IActionResult Insert([FromBody] CRUDModel<ProvinceTbl> model)
		{
			try
			{
				var provinces = this._context.ProvincesUw.Get();
				ProvinceTbl province = new ProvinceTbl
				{
					ProvinceName = model.Value.ProvinceName,
					Description = model.Value.Description,
					CreateDateTime = DateTime.Now,
					IsDelete = false,
					UserID = this._userManager.GetUserId(this.HttpContext.User) ?? "System"
				};
				if (provinces.Any(p => p.ProvinceName == province.ProvinceName))
				{
					return Json(new { action = "repeat", province = province.ProvinceName });
				}
				else
				{
					this._context.ProvincesUw.Create(province);
					this._context.Save();
					return Json(new { action = "insert", province = province.ProvinceName });
				}
			}
			catch (Exception e)
			{
				return Json(new { action = "error", ErrMsg = e.Message });
			}
		}

		public IActionResult Update([FromBody] CRUDModel<ProvinceTbl> model)
		{
			try
			{
				var provinces = this._context.ProvincesUw.Get();

				if (provinces.Any(p => p.ProvinceName == model.Value.ProvinceName))
				{
					return Json(new { action = "repeat", province = model.Value.ProvinceName });
				}
				else
				{
					_repository.UpdateProvince(model);
					return Json(new { action = "update", province = model.Value.ProvinceName });
				}
			}
			catch (Exception e)
			{
				return Json(new { action = "error", ErrMsg = e.Message });
			}
		}

		[HttpPost]
		public IActionResult Delete([FromBody] CRUDModel<ProvinceTbl> model)
		{
			try
			{
				var key = model.Key.ToString();
				var province = this._context.ProvincesUw.GetById(int.Parse(key));
				_repository.DeleteProvince(int.Parse(key));
				return Json(new { action = "delete", province = province.ProvinceName });
			}
			catch (Exception e)
			{
				return Json(new { action = "error", ErrMsg = e.Message });
			}
		}

		[HttpPost]
		public IActionResult Restore([FromBody] CRUDModel<ProvinceTbl> model)
		{
			try
			{
				var key = model.Key.ToString();
				var province = this._context.ProvincesUw.GetById(int.Parse(key));
				_repository.RestoreProvince(int.Parse(key));
				return Json(new { action = "restore", province = province.ProvinceName });
			}
			catch (Exception e)
			{
				return Json(new { action = "error", ErrMsg = e.Message });
			}
		}
	}
}

PayRollProject/Areas/AdminArea/Views/ProvinceManagement/Index.cshtml
@{
	ViewData["AdminTitle"] = "لیست استان ها";

	List<object> toolBarItem = new List<object> { "Add", "Edit", "Update", "Cancel", "Search" };

	toolBarItem.Add(new
	{
		text = "ProvinceDelete",
		tooltipText = "برای حذف استان استفاده میشود",
		id = "provinceDeleteBtn",
		prefixIcon = "e-icons e-delete-3",
		type = "ProvinceDelete",
		title = "حذف استان",
		buttonOption = new
		{
			iconCss = "e-icons e-delete-3",
			cssClass = "btn btn-danger btnDelete"
		}
	});
	toolBarItem.Add(new
	{
		text = "ProvinceRestore",
		tooltipText = "برای بازگرداندن استان استفاده میشود",
		id = "provinceRestoreBtn",
		prefixIcon = "e-icons e-redo",
		type = "ProvinceRestore",
		title = "بازگردانی استان",
		buttonOption = new
		{
			iconCss = "e-icons e-redo",
			cssClass = "badge bg-info btnRestore"
		}
	});

	List<object>
		commands = new List<object> { new { type = "deleteCmd", title = "حذف استان", buttonOption = new { iconCss = "e-icons e-delete", cssClass = "badge bg-danger btnDelete" } }, new { type = "restoreCmd", title = "بازگردانی استان", buttonOption = new { iconCss = "e-icons e-redo", cssClass = "badge bg-info btnRestore" } }, };
}

<link href="~/css/SyncfusionComponentStyle.css" rel="stylesheet" />

<div class="btn-group mb-3" role="group" aria-label="انتخاب نوع نمایش استان">
	<button type="button" class="btn btn-outline-success btn-sm" onclick="updateProvinceList('')">
		<p style="margin-left: 20px;">تعداد استان‌های فعال : <span id="spnRowProvince" style="color: black;"></span></p>
	</button>
	<button type="button" class="btn btn-outline-danger btn-sm" onclick="updateProvinceList('delete')">
		<p style="margin-left: 20px;">تعداد استان‌های حذف شده : <span id="spnRowDelProvince" style="color: red;"></span></p>
	</button>
	<button type="button" class="btn btn-outline-primary btn-sm" onclick="updateProvinceList('all')">
		<p style="margin-left: 20px;">تعداد همه استان‌های ثبت شده: <span id="spnRowAllProvince" style="color: green;"></span></p>
	</button>
</div>

<div class="row bg-white">
	<div class="col-md-12">

		<ejs-grid id="provinceList" created="createdFunc" toolbar="toolBarItem" rowDataBound="rowDataBoundFunc" gridLines="Both"
				  allowExcelExport allowFiltering allowPaging allowSorting
				  toolbarClick="toolbarClickFunc"
				  queryCellInfo="QueryCellFunc" commandClick="commandsClickFunc">
			<e-grid-pagesettings pageSize="10" pageCount="3"></e-grid-pagesettings>
			<e-grid-filtersettings mode="Immediate" type="Menu"></e-grid-filtersettings>
			<e-grid-editsettings allowAdding allowEditing allowDeleting showDeleteConfirmDialog mode="Normal"></e-grid-editsettings>

			<e-grid-columns>
				<e-grid-column field="rowIndex" headerText="ردیف" width="90" allowEditing="false" allowSorting="false" allowFiltering="false" textAlign="Right"></e-grid-column>
				<e-grid-column field="ProvinceName" headerTemplate="#provinceHeader" textAlign="Right"></e-grid-column>
				<e-grid-column field="Description" headerTemplate="#descriptionHeader" textAlign="Right"></e-grid-column>
				<e-grid-column field="ProvinceId" visible="false" isPrimaryKey="true" allowEditing="false"></e-grid-column>
				<e-grid-column commands="commands" headerText="عملیات" textAlign="Center" width="150"></e-grid-column>
			</e-grid-columns>
		</ejs-grid>

	</div>
</div>


@section AdminScripts {


	<!-- برای نمایش ستون نام استان Header Template -->
	<script id="provinceHeader" type="text/x-template">
		<span class="e-icons e-home" style="font-size:15px;"></span> نام استان
	</script>

	<!-- #region برای نمایش ستون توضیحات Header Template -->
	<script id="descriptionHeader" type="text/x-template">
		<span class="e-icons e-header" style="font-size:15px;"></span> توضیحات
	</script>

	<script>
		window.baseUrlProvince = '@Url.Action("FetchProvinceList", "ProvinceManagement", new { area = "AdminArea" })';
		window.insertUrlProvince = '@Url.Action("Insert", "ProvinceManagement", new { area = "AdminArea" })';
		window.updateUrlProvince = '@Url.Action("Update", "ProvinceManagement", new { area = "AdminArea" })';
		window.deleteUrlProvince = '@Url.Action("Delete", "ProvinceManagement", new { area = "AdminArea" })';
		window.restoreUrlProvince = '@Url.Action("Restore", "ProvinceManagement", new { area = "AdminArea" })';
	</script>

	<script src="~/Pages/ProvinceManegement/js/RowIndexScript.js" type="text/javascript" asp-append-version="true"></script>
	<script src="~/Pages/ProvinceManegement/js/CreateFuncScript.js" type="text/javascript" asp-append-version="true"></script>
	<script src="~/Pages/ProvinceManegement/js/CommandScript.js" type="text/javascript" asp-append-version="true"></script>
	<script src="~/Pages/ProvinceManegement/js/QueryCellScript.js" type="text/javascript" asp-append-version="true"></script>
	<script src="~/Pages/ProvinceManegement/js/ToolbarClickScript.js" type="text/javascript" asp-append-version="true"></script>

}